### ISSUE TITLE
No Log to Error Messages

### ISSUE THREAD

**Issue by shopwazs** [carnal0wnage/weirdAAL#55]
Hi Guys,

Got this error message below, but to log file to see the actual error

Check the above error message and fix to use weirdAAL

**Comment by shopwazs** [comment]
Hi ,

The error message was " Check the above error message and fix to use weirdAAL" but there was nothing above that. Also updating bottom library didn't resolve the issues.

Was the tool tested with  (boto3==1.7.75, botocore==1.10.75) ?

**Comment by carnal0wnage** [comment]
that is a exception based on the the perform_credential_check() function - there should be "something" above that.  are you aws keys valid/entered correctly?

**Comment by shopwazs** [comment]
Ok, i might be doing something wrong here, help me find out what it was

Using the recon command below
python3 weirdAAL.py -m recon_all -t MyTarget

Question, what is the value of (MyTarget)

**Comment by carnal0wnage** [comment]
it's whatever you want it to be, it just logs it to the DB

**Comment by carnal0wnage** [comment]
i'm going to close this due to lack of response. Pretty sure weirdAAL couldnt find your .env file.  please open a new issue if you are still stuck.
