### ISSUE TITLE
list modules doesnt work without a valid aws key

### ISSUE THREAD

**Issue by carnal0wnage** [carnal0wnage/weirdAAL#59]
--list (list modules) doesnt work without a valid aws key.  

```
python3 weirdAAL.py --list
The AWS Access Keys are not valid/active
Check the above error message and fix to use weirdAAL
````

this should probably work or run before the access check.  thoughts @cktricky ?

**Comment by cktricky** [comment]
This is resolved in PR #60 ❤️
