### ISSUE TITLE
Support for Boto3 Profile

### ISSUE THREAD

**Issue by jamiesonio** [carnal0wnage/weirdAAL#61]
Hi Chris and contributors,

Thank you for all your great work here ! I was wondering if there was support or planned for leveraging the credentials file in the aws dot directory ?

**Comment by jamiesonio** [comment]
Sorry for the issue guys, I see this now so this looks intentional to protect the user of the script. Going to close the issue. https://github.com/carnal0wnage/weirdAAL/blob/a6c8ab01f5237c24daf052b0961e65cc45b7e577/weirdAAL.py#L20

**Comment by carnal0wnage** [comment]
hey!  yeah we started that way but it got confusing because boto3 kinda magically pics up those values.   We made a decision to override all with the one in the .env file.

**Comment by jamiesonio** [comment]
Yeah I started doing some testing without the .env file and weirdAAL picked up credentials from the EC2 role assigned to my test instances. I only tested IAM and EC2 but most modules seem to work. 

```
$ python3 weirdAAL.py -m iam_get_account_summary -t yolo
### Printing IAM Account Summary ###
{    'AccessKeysPerUserQuota': 2,
     'AccountAccessKeysPresent': 0,
     'AccountMFAEnabled': 0,
     'AccountSigningCertificatesPresent': 0,
     'AssumeRolePolicySizeQuota': 2048,
     'AttachedPoliciesPerGroupQuota': 10,
     'AttachedPoliciesPerRoleQuota': 10,
     'AttachedPoliciesPerUserQuota': 10,
     'GroupPolicySizeQuota': 5120,
     'Groups': 1,
     'GroupsPerUserQuota': 10,
     'GroupsQuota': 300,
     'InstanceProfiles': 3,
     'InstanceProfilesQuota': 1000,
     'MFADevices': 1,
     'MFADevicesInUse': 0,
     'Policies': 3,
     'PoliciesQuota': 1500,
     'PolicySizeQuota': 6144,
     'PolicyVersionsInUse': 14,
     'PolicyVersionsInUseQuota': 10000,
     'Providers': 0,
     'RolePolicySizeQuota': 10240,
     'Roles': 24,
     'RolesQuota': 1000,
     'ServerCertificates': 0,
     'ServerCertificatesQuota': 20,
     'SigningCertificatesPerUserQuota': 2,
     'UserPolicySizeQuota': 2048,
     'Users': 2,
     'UsersQuota': 5000,
     'VersionsPerPolicyQuota': 5}
```
